# Generated by Django 4.2.16 on 2024-12-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('valor', models.BigIntegerField()),
            ],
        ),
    ]
